version: '3.9'
services:
  first_classification:
    build:
        context: ./docker
        dockerfile: x86.dockerfile
    runtime: nvidia
    environment:
        - DISPLAY=$DISPLAY
    volumes:
        - ./1st_classification:/1st_classification
        - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /1st_classification
    tty: true
    network_mode: host
    command: bash
    entrypoint: [
      "python3",
      "/1st_classification/server.py"
    ]
